[package]
name = "rhashmap"
version = "0.1.0"
authors = ["stereobooster <stereobooster@gmail.com>"]
repository = "https://github.com/stereobooster/rhashmap"
readme = "README.md"
license = "MIT"

[dependencies]
crossbeam = "0.2"
